applicationName: contents-api

phase: LOCAL

mysql:
  db_url: .
  pool_recycle: 3600

security:
  secret_key: .
  algorithm: HS256
  expires_delta: 1440

aws:
  region: ap-northeast-2
  bucket: playtherapy-contents
  access_key: .
  secret_key: .
