applicationName: contents-api

phase: ALPHA

mysql:
  db_url: .
  pool_recycle: 3600

security:
  secret_key: .
  algorithm: HS256
  expires_delta: 60

aws:
  region: ap-northeast-2
  bucket: playtherapy-contents
  access_key: .
  secret_key: .
